# Version
targetJavaVersion=17
group=su.plo.voice
version=3.1.11

# Gradle args
org.gradle.jvmargs=-Xmx2G -Dkotlin.daemon.jvm.options=-Xmx1G
org.gradle.workers.max=2
kotlin.stdlib.default.dependency=false

# default 3
org.gradle.internal.repository.max.tentatives=5
org.gradle.java.installations.paths=C:/Users/Admin/.gradle/jdks/eclipse_adoptium-17-amd64-windows/jdk-17.0.17+10
